# app.py
import time
from core.graph import build_graph
from core.state import ResearchState
from langchain_core.messages import HumanMessage
from dotenv import load_dotenv

load_dotenv()


def print_banner():
    print("""
╔══════════════════════════════════════════════╗
║     🔬 Autonomous Research Agent v3.0       ║
║     Built with LangGraph + Multi-Agent      ║
╚══════════════════════════════════════════════╝

Depth options:
  quick    → fast overview (2-3 minutes)
  standard → balanced report (4-6 minutes)
  deep     → comprehensive (8-12 minutes)
""")


def run_research(topic: str, depth: str = "standard"):
    """Run the full research pipeline"""
    graph = build_graph()
    config = {"configurable": {"thread_id": f"research_{int(time.time())}"}}

    print(f"\n🚀 Starting research on: '{topic}'")
    print(f"   Depth: {depth}")
    print(f"   Started: {time.strftime('%H:%M:%S')}\n")

    start = time.time()

    # Stream execution
    final_state = None
    for step in graph.stream(
        {
            "topic":      topic,
            "depth":      depth,
            "messages":   [],
            "raw_sources":  [],
            "key_insights": [],
            "completed":    [],
            "iteration":    0,
            "start_time":   start
        },
        config=config,
        stream_mode="updates"
    ):
        for node, update in step.items():
            status = update.get("status", "")
            if status:
                elapsed = time.time() - start
                print(f"   [{elapsed:.0f}s] {node.upper()}: {status}")

        final_state = step

    elapsed = time.time() - start

    # Get final state
    state = graph.get_state(config).values

    print(f"\n{'='*60}")
    print(f"✅ Research Complete in {elapsed:.0f}s")
    print(f"   Quality Score: {state.get('quality_score', 'N/A')}/10")
    print(f"   Word Count:    {state.get('word_count', 'N/A')}")
    print(f"   Sources Found: {len(state.get('raw_sources', []))}")
    print(f"{'='*60}\n")

    return state


def save_report(state: dict, filename: str = None):
    """Save report to markdown file"""
    if not filename:
        safe_topic = state['topic'].replace(" ", "_")[:30]
        filename = f"report_{safe_topic}_{int(time.time())}.md"

    report = state.get("final_report", "No report generated")
    sources = state.get("raw_sources", [])

    content = f"{report}\n\n---\n*Generated by Autonomous Research Agent*\n"
    if sources:
        content += f"\n**Sources:**\n" + "\n".join(f"- {s}" for s in sources)

    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"💾 Report saved: {filename}")
    return filename


def main():
    print_banner()

    while True:
        topic = input("📝 Research topic (or 'quit'): ").strip()
        if topic.lower() in ["quit", "exit", "q"]:
            print("\n👋 Goodbye!\n")
            break
        if not topic:
            continue

        depth = input("🔍 Depth [quick/standard/deep] (default=standard): ").strip()
        if depth not in ["quick", "standard", "deep"]:
            depth = "standard"

        state = run_research(topic, depth)

        print("\n" + "="*60)
        print("📄 FINAL REPORT")
        print("="*60)
        print(state.get("final_report", "Report not generated"))

        save = input("\n💾 Save report to file? [y/n]: ").strip().lower()
        if save == "y":
            save_report(state)

        again = input("\n🔄 Research another topic? [y/n]: ").strip().lower()
        if again != "y":
            print("\n👋 Goodbye!\n")
            break


if __name__ == "__main__":
    main()